# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение датчиков
GET {{baseUrl}}/get_sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/create_sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/update_sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/edit_measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/get_sensors/1/
Content-Type: application/json
