# Generated by Django 5.0.2 on 2024-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="lte_exists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phone",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="phone",
            name="price",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="phone",
            name="release_date",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="phone",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
