# Generated by Django 5.0.2 on 2024-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_phone_image_phone_lte_exists_phone_name_phone_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(
                verbose_name=models.CharField(blank=True, max_length=50)
            ),
        ),
    ]
